version: 2.1

commands:
  build_and_run_unit_tests_single_chain:
    steps:
      - checkout
      - run:
          name: Run CMake
          command: |
            mkdir build && cd build && \
            cmake -DCMAKE_BUILD_TYPE=Debug -DCHAIN_SRC_ROOT=/work/bitcoin -DCHAIN_TYPE=$CHAIN_TYPE -DJOBS=2  ..
      - run:
          name: Build btcpool
          command: cd build && make -j2
      - run:
          name: Run unit tests
          command: cd build && make test
      - run:
          name: Send failure notification
          command: if [ -n "$BEARYCHAT_WEBHOOK" ]; then curl $BEARYCHAT_WEBHOOK -H 'Content-Type:application/json' -d "{\"text\":\"[$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$CIRCLE_JOB/$CIRCLE_BUILD_NUM]($CIRCLE_BUILD_URL) failed\"}"; fi
          when: on_fail

jobs:
  build_and_run_unit_tests_bch:
    docker:
      - image: btccom/btcpool_build:bch-0.18.5
    steps:
      - build_and_run_unit_tests_single_chain
  build_and_run_unit_tests_btc:
    docker:
      - image: btccom/btcpool_build:btc-0.16.3
    steps:
      - build_and_run_unit_tests_single_chain
  build_and_run_unit_tests_sbtc:
    docker:
      - image: btccom/btcpool_build:sbtc-0.16.2
    steps:
      - build_and_run_unit_tests_single_chain
  build_and_run_unit_tests_ubtc:
    docker:
      - image: btccom/btcpool_build:ubtc-2.3.0.1
    steps:
      - build_and_run_unit_tests_single_chain

workflows:
  build_and_run_unit_tests_all_chains:
    jobs:
      - build_and_run_unit_tests_bch
      - build_and_run_unit_tests_btc
      - build_and_run_unit_tests_sbtc
      - build_and_run_unit_tests_ubtc
